import { nutrition_pdf_settings, training_pdf_settings } from '@prisma/client';
import { prisma } from '../../lib/prisma';

// Mirrors the column defaults declared in schema.prisma / migrations
// 067_split_pdf_settings_by_plan_type.js + 091_pdf_branding_profiles.js — used
// only when a workspace has saved no profiles of a type yet, so a GET never
// has to write a row just to answer a read. `name`/`is_default` describe this
// as the workspace's implicit default profile.
const DEFAULT_NUTRITION_PDF_SETTINGS: Omit<nutrition_pdf_settings, 'id' | 'workspace_id' | 'updated_at'> = {
    name:                           'Default',
    is_default:                     true,
    coach_name:                     'FitForce',
    footer_text:                    'Generated by FitForce',
    primary_color:                  '#007AFF',
    show_notes:                     true,
    show_alternatives:              true,
    show_macros_summary:            true,
    show_cycle_totals:              true,
    show_meal_totals:               true,
    logo_url:                       null,
    header_text_color:              '#FFFFFF',
    show_food_calories:             true,
    table_header_bg_color:          '#E8E8ED',
    table_alt_bg_color:             '#F9F9FB',
    show_food_macros:               true,
    show_cover_page:                true,
    show_plan_summary_page:         true,
    show_meal_summary_page:         true,
    show_cycle_summary_page:        true,
    page_bg_image_url:              null,
    cover_image_url:                null,
    cover_title:                    'Nutrition Plan',
    cover_subtitle:                 '',
    summary_bg_image_url:           null,
    page_width:                     595.28,
    page_height:                    841.89,
    plan_summary_bg_image_url:      null,
    meal_summary_bg_image_url:      null,
    cycle_summary_bg_image_url:     null,
    back_cover_bg_image_url:        null,
    show_back_cover_page:           false,
    max_meals_per_page:             0,
    meals_content_primary_color:    null,
    plan_summary_primary_color:     null,
    cycle_summary_primary_color:    null,
    show_cover_header:              true,
    show_cover_title:               true,
    show_cover_subtitle:            true,
    show_cover_client_name:         true,
    body_text_color:                '#1A1A1A',
};

const DEFAULT_TRAINING_PDF_SETTINGS: Omit<training_pdf_settings, 'id' | 'workspace_id' | 'updated_at'> = {
    name:                           'Default',
    is_default:                     true,
    coach_name:                     'FitForce',
    footer_text:                    'Generated by FitForce',
    primary_color:                  '#007AFF',
    header_text_color:              '#FFFFFF',
    table_header_bg_color:          '#E8E8ED',
    table_alt_bg_color:             '#F9F9FB',
    logo_url:                       null,
    show_cover_page:                true,
    show_back_cover_page:           false,
    show_plan_summary_page:         true,
    cover_title:                    'Training Plan',
    cover_subtitle:                 '',
    cover_image_url:                null,
    page_bg_image_url:              null,
    back_cover_bg_image_url:        null,
    page_width:                     595.28,
    page_height:                    841.89,
    show_notes:                     true,
    show_exercise_notes:            true,
    show_exercise_equipment:        true,
    show_sets_detail:               true,
    show_day_summary_page:          true,
    day_summary_bg_image_url:       null,
    exercise_content_primary_color: null,
    day_summary_primary_color:      null,
    max_exercises_per_page:         0,
    show_cover_header:              true,
    show_cover_title:               true,
    show_cover_subtitle:            true,
    show_cover_client_name:         true,
    body_text_color:                '#1A1A1A',
    show_exercise_thumbnail:        true,
    exercise_thumbnail_size:        'medium',
};

// The synthesized default profile for a workspace that has none saved yet. id
// is '' so callers can tell "not persisted" — the settings page turns its
// first save into a real row.
function synthesizedNutritionDefault(workspaceId: string): nutrition_pdf_settings {
    return { ...DEFAULT_NUTRITION_PDF_SETTINGS, id: '', workspace_id: workspaceId, updated_at: null };
}

function synthesizedTrainingDefault(workspaceId: string): training_pdf_settings {
    return { ...DEFAULT_TRAINING_PDF_SETTINGS, id: '', workspace_id: workspaceId, updated_at: null };
}

// ---------------------------------------------------------------------------
// List every profile of a type for a workspace. Default first, then by name.
// A workspace with no saved rows gets a one-element list holding the
// synthesized default, so the settings page always has something to show.
// ---------------------------------------------------------------------------

export async function listNutritionPdfProfiles(workspaceId: string): Promise<nutrition_pdf_settings[]> {
    const rows = await prisma.nutrition_pdf_settings.findMany({
        where:   { workspace_id: workspaceId },
        orderBy: [{ is_default: 'desc' }, { name: 'asc' }],
    });
    return rows.length ? rows : [synthesizedNutritionDefault(workspaceId)];
}

export async function listTrainingPdfProfiles(workspaceId: string): Promise<training_pdf_settings[]> {
    const rows = await prisma.training_pdf_settings.findMany({
        where:   { workspace_id: workspaceId },
        orderBy: [{ is_default: 'desc' }, { name: 'asc' }],
    });
    return rows.length ? rows : [synthesizedTrainingDefault(workspaceId)];
}

// ---------------------------------------------------------------------------
// Resolve the one profile an export/preview should use. A named profileId that
// exists in this workspace wins; otherwise the workspace's default profile;
// otherwise the synthesized default. Never throws and always returns a usable
// object — an export must always be able to produce a PDF (see DECISIONS.md,
// "fall back to the default profile").
// ---------------------------------------------------------------------------

export async function getNutritionPdfProfile(workspaceId: string, profileId?: string | null): Promise<nutrition_pdf_settings> {
    if (profileId) {
        const byId = await prisma.nutrition_pdf_settings.findFirst({ where: { id: profileId, workspace_id: workspaceId } });
        if (byId) return byId;
    }
    const fallback = await prisma.nutrition_pdf_settings.findFirst({
        where:   { workspace_id: workspaceId },
        orderBy: [{ is_default: 'desc' }, { name: 'asc' }],
    });
    return fallback ?? synthesizedNutritionDefault(workspaceId);
}

export async function getTrainingPdfProfile(workspaceId: string, profileId?: string | null): Promise<training_pdf_settings> {
    if (profileId) {
        const byId = await prisma.training_pdf_settings.findFirst({ where: { id: profileId, workspace_id: workspaceId } });
        if (byId) return byId;
    }
    const fallback = await prisma.training_pdf_settings.findFirst({
        where:   { workspace_id: workspaceId },
        orderBy: [{ is_default: 'desc' }, { name: 'asc' }],
    });
    return fallback ?? synthesizedTrainingDefault(workspaceId);
}

// Back-compat aliases — "the workspace's default profile". Used by the live
// preview endpoint and the smoke-test scripts, neither of which selects a
// profile.
export const getOrDefaultNutritionPdfSettings = (workspaceId: string) => getNutritionPdfProfile(workspaceId, null);
export const getOrDefaultTrainingPdfSettings  = (workspaceId: string) => getTrainingPdfProfile(workspaceId, null);
