import { VisualPdfConfig } from '@/components/VisualPdfBuilder';

export interface TemplatePreset {
  id: string;
  name: string;
  description: string;
  category: 'minimalist' | 'professional' | 'colorful' | 'compact' | 'detailed';
  config: VisualPdfConfig;
}

export const workoutPresets: TemplatePreset[] = [
  {
    id: 'workout-minimalist',
    name: 'Minimalist',
    description: 'Clean and simple design with lots of whitespace',
    category: 'minimalist',
    config: {
      introPage: {
        enabled: false,
      },
      endPage: {
        enabled: false,
      },
      dayPages: {
        layout: 'vertical',
        daysPerPage: 1,
        backgroundColor: '#ffffff',
        textColor: '#000000',
        fontSize: {
          dayTitle: 20,
          exerciseName: 14,
          details: 11,
        },
        table: {
          headerBackground: '#f5f5f5',
          headerTextColor: '#000000',
          borderColor: '#e0e0e0',
          stripeColor: '#fafafa',
        },
        options: {
          showGifImage: false,
          showExerciseName: true,
          showExerciseDescription: false,
          showSetRest: true,
          showSetTempo: false,
          showSetRir: false,
        },
      },
      options: {
        pageSize: 'A4',
        orientation: 'portrait',
        fontFamily: 'Helvetica',
        primaryColor: '#000000',
        secondaryColor: '#666666',
      },
    },
  },
  {
    id: 'workout-professional',
    name: 'Professional',
    description: 'Corporate look with formal colors and comprehensive details',
    category: 'professional',
    config: {
      introPage: {
        enabled: true,
        showPlanTitle: true,
        showWorkspaceName: true,
        showClientName: true,
        backgroundColor: '#ffffff',
        titleColor: '#1a1a1a',
        titleSize: 28,
      },
      endPage: {
        enabled: true,
        showThankYouMessage: true,
        showContactInfo: true,
        backgroundColor: '#ffffff',
        textColor: '#1a1a1a',
        customMessage: 'Thank you for choosing our services.',
      },
      dayPages: {
        layout: 'vertical',
        daysPerPage: 1,
        backgroundColor: '#ffffff',
        textColor: '#1a1a1a',
        fontSize: {
          dayTitle: 18,
          exerciseName: 12,
          details: 10,
        },
        table: {
          headerBackground: '#2c3e50',
          headerTextColor: '#ffffff',
          borderColor: '#34495e',
          stripeColor: '#ecf0f1',
        },
        options: {
          showGifImage: true,
          gifHeight: 120,
          showExerciseName: true,
          showExerciseDescription: true,
          showSetRest: true,
          showSetTempo: true,
          showSetRir: true,
        },
      },
      options: {
        pageSize: 'A4',
        orientation: 'portrait',
        fontFamily: 'Times-Roman',
        primaryColor: '#2c3e50',
        secondaryColor: '#34495e',
      },
    },
  },
  {
    id: 'workout-colorful',
    name: 'Colorful',
    description: 'Vibrant colors and playful design',
    category: 'colorful',
    config: {
      introPage: {
        enabled: true,
        showPlanTitle: true,
        showWorkspaceName: true,
        showClientName: true,
        backgroundColor: '#f0f4ff',
        titleColor: '#6366f1',
        titleSize: 36,
      },
      endPage: {
        enabled: true,
        showThankYouMessage: true,
        showContactInfo: true,
        backgroundColor: '#f0f4ff',
        textColor: '#6366f1',
        customMessage: 'Thank you for choosing us!',
      },
      dayPages: {
        layout: 'vertical',
        daysPerPage: 1,
        backgroundColor: '#ffffff',
        textColor: '#1e293b',
        fontSize: {
          dayTitle: 20,
          exerciseName: 13,
          details: 11,
        },
        table: {
          headerBackground: '#6366f1',
          headerTextColor: '#ffffff',
          borderColor: '#818cf8',
          stripeColor: '#eef2ff',
        },
        options: {
          showGifImage: true,
          gifHeight: 150,
          showExerciseName: true,
          showExerciseDescription: true,
          showSetRest: true,
          showSetTempo: true,
          showSetRir: true,
        },
      },
      options: {
        pageSize: 'A4',
        orientation: 'portrait',
        fontFamily: 'Helvetica',
        primaryColor: '#6366f1',
        secondaryColor: '#818cf8',
      },
    },
  },
  {
    id: 'workout-compact',
    name: 'Compact',
    description: 'Maximum information density, minimal space',
    category: 'compact',
    config: {
      introPage: {
        enabled: false,
      },
      endPage: {
        enabled: false,
      },
      dayPages: {
        layout: 'vertical',
        daysPerPage: 2,
        backgroundColor: '#ffffff',
        textColor: '#000000',
        fontSize: {
          dayTitle: 16,
          exerciseName: 10,
          details: 8,
        },
        table: {
          headerBackground: '#f5f5f5',
          headerTextColor: '#000000',
          borderColor: '#d0d0d0',
          stripeColor: '#f9f9f9',
        },
        options: {
          showGifImage: false,
          showExerciseName: true,
          showExerciseDescription: false,
          showSetRest: true,
          showSetTempo: false,
          showSetRir: false,
        },
      },
      options: {
        pageSize: 'A4',
        orientation: 'portrait',
        fontFamily: 'Courier',
        primaryColor: '#000000',
        secondaryColor: '#333333',
      },
    },
  },
  {
    id: 'workout-detailed',
    name: 'Detailed',
    description: 'All options enabled with comprehensive information',
    category: 'detailed',
    config: {
      introPage: {
        enabled: true,
        showPlanTitle: true,
        showWorkspaceName: true,
        showClientName: true,
        backgroundColor: '#ffffff',
        titleColor: '#1a1a1a',
        titleSize: 32,
      },
      endPage: {
        enabled: true,
        showThankYouMessage: true,
        showContactInfo: true,
        backgroundColor: '#ffffff',
        textColor: '#1a1a1a',
        customMessage: 'Thank you for choosing us!',
      },
      dayPages: {
        layout: 'vertical',
        daysPerPage: 1,
        backgroundColor: '#ffffff',
        textColor: '#000000',
        fontSize: {
          dayTitle: 18,
          exerciseName: 12,
          details: 10,
        },
        table: {
          headerBackground: '#f5f7ff',
          headerTextColor: '#1a1a1a',
          borderColor: '#d4daec',
          stripeColor: '#f0f4ff',
        },
        options: {
          showGifImage: true,
          gifHeight: 140,
          showExerciseName: true,
          showExerciseDescription: true,
          showSetRest: true,
          showSetTempo: true,
          showSetRir: true,
        },
      },
      options: {
        pageSize: 'A4',
        orientation: 'portrait',
        fontFamily: 'Alexandria',
        primaryColor: '#3366cc',
        secondaryColor: '#333333',
      },
    },
  },
];

export const nutritionPresets: TemplatePreset[] = [
  {
    id: 'nutrition-minimalist',
    name: 'Minimalist',
    description: 'Clean and simple design with essential information only',
    category: 'minimalist',
    config: {
      introPage: {
        enabled: false,
      },
      endPage: {
        enabled: false,
      },
      dayPages: {
        layout: 'vertical',
        daysPerPage: 2,
        backgroundColor: '#ffffff',
        textColor: '#000000',
        fontSize: {
          dayTitle: 18,
          exerciseName: 12,
          details: 10,
        },
        table: {
          headerBackground: '#f5f5f5',
          headerTextColor: '#000000',
          borderColor: '#e0e0e0',
          stripeColor: '#fafafa',
        },
        options: {
          showMealNames: true,
          showMealTimes: false,
          showFoodItems: true,
          showQuantities: true,
          showMacros: false,
          showCalories: false,
          showProtein: false,
          showCarbs: false,
          showFat: false,
          showMealTotalCalories: false,
          showDayTotalCalories: false,
          showMealNotes: false,
        },
      },
      options: {
        pageSize: 'A4',
        orientation: 'portrait',
        fontFamily: 'Helvetica',
        primaryColor: '#000000',
        secondaryColor: '#666666',
      },
    },
  },
  {
    id: 'nutrition-professional',
    name: 'Professional',
    description: 'Corporate look with comprehensive macro tracking',
    category: 'professional',
    config: {
      introPage: {
        enabled: true,
        showPlanTitle: true,
        showWorkspaceName: true,
        showClientName: true,
        backgroundColor: '#ffffff',
        titleColor: '#1a1a1a',
        titleSize: 28,
      },
      endPage: {
        enabled: true,
        showThankYouMessage: true,
        showContactInfo: true,
        backgroundColor: '#ffffff',
        textColor: '#1a1a1a',
        customMessage: 'Thank you for choosing our services.',
      },
      dayPages: {
        layout: 'vertical',
        daysPerPage: 1,
        backgroundColor: '#ffffff',
        textColor: '#1a1a1a',
        fontSize: {
          dayTitle: 18,
          exerciseName: 12,
          details: 10,
        },
        table: {
          headerBackground: '#2c3e50',
          headerTextColor: '#ffffff',
          borderColor: '#34495e',
          stripeColor: '#ecf0f1',
        },
        options: {
          showMealNames: true,
          showMealTimes: true,
          showFoodItems: true,
          showQuantities: true,
          showMacros: true,
          showCalories: true,
          showProtein: true,
          showCarbs: true,
          showFat: true,
          showMealTotalCalories: true,
          showDayTotalCalories: true,
          showMealNotes: true,
        },
      },
      options: {
        pageSize: 'A4',
        orientation: 'portrait',
        fontFamily: 'Times-Roman',
        primaryColor: '#2c3e50',
        secondaryColor: '#34495e',
      },
    },
  },
  {
    id: 'nutrition-colorful',
    name: 'Colorful',
    description: 'Vibrant design with visual appeal',
    category: 'colorful',
    config: {
      introPage: {
        enabled: true,
        showPlanTitle: true,
        showWorkspaceName: true,
        showClientName: true,
        backgroundColor: '#fef3c7',
        titleColor: '#f59e0b',
        titleSize: 36,
      },
      endPage: {
        enabled: true,
        showThankYouMessage: true,
        showContactInfo: true,
        backgroundColor: '#fef3c7',
        textColor: '#f59e0b',
        customMessage: 'Thank you for choosing us!',
      },
      dayPages: {
        layout: 'vertical',
        daysPerPage: 1,
        backgroundColor: '#ffffff',
        textColor: '#1e293b',
        fontSize: {
          dayTitle: 20,
          exerciseName: 13,
          details: 11,
        },
        table: {
          headerBackground: '#f59e0b',
          headerTextColor: '#ffffff',
          borderColor: '#fbbf24',
          stripeColor: '#fef3c7',
        },
        options: {
          showMealNames: true,
          showMealTimes: true,
          showFoodItems: true,
          showQuantities: true,
          showMacros: true,
          showCalories: true,
          showProtein: true,
          showCarbs: true,
          showFat: true,
          showMealTotalCalories: true,
          showDayTotalCalories: true,
          showMealNotes: false,
        },
      },
      options: {
        pageSize: 'A4',
        orientation: 'portrait',
        fontFamily: 'Helvetica',
        primaryColor: '#f59e0b',
        secondaryColor: '#fbbf24',
      },
    },
  },
  {
    id: 'nutrition-compact',
    name: 'Compact',
    description: 'Maximum information in minimal space',
    category: 'compact',
    config: {
      introPage: {
        enabled: false,
      },
      endPage: {
        enabled: false,
      },
      dayPages: {
        layout: 'horizontal',
        daysPerPage: 3,
        backgroundColor: '#ffffff',
        textColor: '#000000',
        fontSize: {
          dayTitle: 14,
          exerciseName: 10,
          details: 8,
        },
        table: {
          headerBackground: '#f5f5f5',
          headerTextColor: '#000000',
          borderColor: '#d0d0d0',
          stripeColor: '#f9f9f9',
        },
        options: {
          showMealNames: true,
          showMealTimes: false,
          showFoodItems: true,
          showQuantities: true,
          showMacros: true,
          showCalories: true,
          showProtein: false,
          showCarbs: false,
          showFat: false,
          showMealTotalCalories: true,
          showDayTotalCalories: true,
          showMealNotes: false,
        },
      },
      options: {
        pageSize: 'A4',
        orientation: 'portrait',
        fontFamily: 'Courier',
        primaryColor: '#000000',
        secondaryColor: '#333333',
      },
    },
  },
  {
    id: 'nutrition-detailed',
    name: 'Detailed',
    description: 'Complete information with all options enabled',
    category: 'detailed',
    config: {
      introPage: {
        enabled: true,
        showPlanTitle: true,
        showWorkspaceName: true,
        showClientName: true,
        backgroundColor: '#ffffff',
        titleColor: '#1a1a1a',
        titleSize: 32,
      },
      endPage: {
        enabled: true,
        showThankYouMessage: true,
        showContactInfo: true,
        backgroundColor: '#ffffff',
        textColor: '#1a1a1a',
        customMessage: 'Thank you for choosing us!',
      },
      dayPages: {
        layout: 'vertical',
        daysPerPage: 1,
        backgroundColor: '#ffffff',
        textColor: '#000000',
        fontSize: {
          dayTitle: 18,
          exerciseName: 12,
          details: 10,
        },
        table: {
          headerBackground: '#f5f7ff',
          headerTextColor: '#1a1a1a',
          borderColor: '#d4daec',
          stripeColor: '#f0f4ff',
        },
        options: {
          showMealNames: true,
          showMealTimes: true,
          showFoodItems: true,
          showQuantities: true,
          showMacros: true,
          showCalories: true,
          showProtein: true,
          showCarbs: true,
          showFat: true,
          showMealTotalCalories: true,
          showDayTotalCalories: true,
          showMealNotes: true,
        },
      },
      options: {
        pageSize: 'A4',
        orientation: 'portrait',
        fontFamily: 'Alexandria',
        primaryColor: '#3366cc',
        secondaryColor: '#333333',
      },
    },
  },
];

export function getPresetsForKind(kind: 'workout' | 'nutrition'): TemplatePreset[] {
  return kind === 'workout' ? workoutPresets : nutritionPresets;
}

export function getPresetById(id: string): TemplatePreset | undefined {
  return [...workoutPresets, ...nutritionPresets].find(preset => preset.id === id);
}

