// Nutrition and training PDF exports used to share one `pdf_settings` row per
// workspace — same logo, same colors, same cover image for both. Splitting
// into two fully independent tables so a workspace can brand its nutrition
// and training PDFs completely differently, with zero shared assets.
//
// `pdf_settings` is renamed to `nutrition_pdf_settings` (keeps its existing
// data — the nutrition-relevant fields it already had) and its training-only
// columns are dropped. `training_pdf_settings` is a new table, seeded from
// each existing row's shared/generic fields (branding, colors, cover) so a
// workspace that already configured PDF branding doesn't start from a blank
// slate for training — only the training-specific toggles start at defaults.
exports.up = async (pgm) => {
    await pgm.db.query(`
        ALTER TABLE pdf_settings RENAME TO nutrition_pdf_settings;
        ALTER TABLE nutrition_pdf_settings RENAME CONSTRAINT pdf_settings_pkey TO nutrition_pdf_settings_pkey;
        ALTER TABLE nutrition_pdf_settings RENAME CONSTRAINT pdf_settings_workspace_id_fkey TO nutrition_pdf_settings_workspace_id_fkey;
        ALTER INDEX pdf_settings_coach_id_key RENAME TO nutrition_pdf_settings_workspace_id_key;

        ALTER TABLE nutrition_pdf_settings
            DROP COLUMN show_exercise_notes,
            DROP COLUMN show_exercise_equipment,
            DROP COLUMN show_sets_detail,
            DROP COLUMN show_day_summary_page,
            DROP COLUMN day_summary_bg_image_url,
            DROP COLUMN exercise_content_primary_color,
            DROP COLUMN day_summary_primary_color,
            DROP COLUMN max_exercises_per_page;

        ALTER TABLE nutrition_pdf_settings ALTER COLUMN cover_title SET DEFAULT 'Nutrition Plan';

        CREATE TABLE training_pdf_settings (
            id                              TEXT      PRIMARY KEY,
            workspace_id                    TEXT      UNIQUE REFERENCES workspaces(id) ON DELETE CASCADE,
            coach_name                      TEXT      NOT NULL DEFAULT 'FitForce',
            footer_text                     TEXT      NOT NULL DEFAULT 'Generated by FitForce',
            primary_color                   TEXT      NOT NULL DEFAULT '#007AFF',
            header_text_color               TEXT      NOT NULL DEFAULT '#FFFFFF',
            table_header_bg_color           TEXT      NOT NULL DEFAULT '#E8E8ED',
            table_alt_bg_color              TEXT      NOT NULL DEFAULT '#F9F9FB',
            logo_url                        TEXT,
            show_cover_page                 BOOLEAN   NOT NULL DEFAULT TRUE,
            show_back_cover_page            BOOLEAN   NOT NULL DEFAULT FALSE,
            show_plan_summary_page          BOOLEAN   NOT NULL DEFAULT TRUE,
            cover_title                     TEXT      NOT NULL DEFAULT 'Training Plan',
            cover_subtitle                  TEXT      DEFAULT '',
            cover_image_url                 TEXT,
            page_bg_image_url               TEXT,
            back_cover_bg_image_url         TEXT,
            page_width                      REAL      NOT NULL DEFAULT 595.28,
            page_height                     REAL      NOT NULL DEFAULT 841.89,
            show_notes                      BOOLEAN   NOT NULL DEFAULT TRUE,
            show_exercise_notes             BOOLEAN   NOT NULL DEFAULT TRUE,
            show_exercise_equipment         BOOLEAN   NOT NULL DEFAULT TRUE,
            show_sets_detail                BOOLEAN   NOT NULL DEFAULT TRUE,
            show_day_summary_page           BOOLEAN   NOT NULL DEFAULT TRUE,
            day_summary_bg_image_url        TEXT,
            exercise_content_primary_color  TEXT,
            day_summary_primary_color       TEXT,
            max_exercises_per_page          INTEGER   NOT NULL DEFAULT 0,
            updated_at                      TIMESTAMP DEFAULT NOW()
        );

        INSERT INTO training_pdf_settings (
            id, workspace_id, coach_name, footer_text, primary_color, header_text_color,
            table_header_bg_color, table_alt_bg_color, logo_url,
            show_cover_page, show_back_cover_page, show_plan_summary_page,
            cover_subtitle, cover_image_url, page_bg_image_url, back_cover_bg_image_url,
            page_width, page_height, show_notes
        )
        SELECT
            workspace_id || '_training_pdf_settings', workspace_id, coach_name, footer_text, primary_color, header_text_color,
            table_header_bg_color, table_alt_bg_color, logo_url,
            show_cover_page, show_back_cover_page, show_plan_summary_page,
            cover_subtitle, cover_image_url, page_bg_image_url, back_cover_bg_image_url,
            page_width, page_height, show_notes
        FROM nutrition_pdf_settings
        WHERE workspace_id IS NOT NULL;
    `);
};

exports.down = async (pgm) => {
    await pgm.db.query(`
        DROP TABLE IF EXISTS training_pdf_settings;

        ALTER TABLE nutrition_pdf_settings ALTER COLUMN cover_title SET DEFAULT 'Plan';

        ALTER TABLE nutrition_pdf_settings
            ADD COLUMN show_exercise_notes             BOOLEAN NOT NULL DEFAULT TRUE,
            ADD COLUMN show_exercise_equipment          BOOLEAN NOT NULL DEFAULT TRUE,
            ADD COLUMN show_sets_detail                 BOOLEAN NOT NULL DEFAULT TRUE,
            ADD COLUMN show_day_summary_page            BOOLEAN NOT NULL DEFAULT TRUE,
            ADD COLUMN day_summary_bg_image_url         TEXT,
            ADD COLUMN exercise_content_primary_color   TEXT,
            ADD COLUMN day_summary_primary_color        TEXT,
            ADD COLUMN max_exercises_per_page           INTEGER NOT NULL DEFAULT 0;

        ALTER INDEX nutrition_pdf_settings_workspace_id_key RENAME TO pdf_settings_coach_id_key;
        ALTER TABLE nutrition_pdf_settings RENAME CONSTRAINT nutrition_pdf_settings_workspace_id_fkey TO pdf_settings_workspace_id_fkey;
        ALTER TABLE nutrition_pdf_settings RENAME CONSTRAINT nutrition_pdf_settings_pkey TO pdf_settings_pkey;
        ALTER TABLE nutrition_pdf_settings RENAME TO pdf_settings;
    `);
};
